### ISSUE TITLE
How to get in touch with the SSI-community?

### ISSUE THREAD

**Issue by Arxcis** [DIN-Foundation/bsc-ntnu-2021#8]
There are many people I could reach out to. Where to start? :thinking: 

Summary of potential contact points:
- DIF has a ~Discord~ **Slack**-server
- There are mailing lists.
- Some people are having a bi-weekly call.

Why do we need to contact them?
- To avoid duplication of effort.
- Focusing on what the community needs the most.
- To get help to solve this issue #7

**Comment by vongohren** [comment]
@Arxcis dif has a slack, you can join as a single person. The bottom of this page: https://identity.foundation/join/ it says individial. Leads to this form: https://docs.google.com/forms/d/e/1FAIpQLSc9jyJiSfu8kb6mLZK4nHfRHQQjb7XSzlmdfWfYlxJJg3qM8A/viewform

People like Manu, Orie and Wayne are very open to talk about their understanding of interopability issues. I have their contact info and would be glad to introduce you guys over email. Im not close, but been on one on one calls with all three, as well slept in the same house as Wayne for a weekend.

So if I introduce you, per email there is a bigger chance to get that meeting. They might send you onwards to another person to take the talk, but it is a start.

If you get into the slack, we can start a conversation there as well.

**Comment by Arxcis** [comment]
Ok. I will focus on getting into the Slack first :+1:

**Comment by Arxcis** [comment]
I think this answer has been answered very well by @vongohren . :+1: 

**Summary**
- Join the DIF foundation
- Talk directly to key individuals there via mail or Slack.
- Async communication is preferred over calls, as long as the questions are trivial to answer.
